apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scea-db-pvc
  namespace: scea
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
