apiVersion: v1
kind: Secret
metadata:
  name: scea-db-secret
  namespace: scea
type: Opaque
stringData:
  POSTGRES_DB: scea
  POSTGRES_USER: mavigo
  POSTGRES_PASSWORD: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: scea-mail-secret
  namespace: scea
type: Opaque
stringData:
  SPRING_MAIL_USERNAME: ucsalscea@gmail.com
  SPRING_MAIL_PASSWORD: aiuv yvmt ftoh gdos
