server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: back

  datasource:
    url: jdbc:postgresql://db:5432/scea
    username: ${SPRING_DATASOURCE_USERNAME:mavigo}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:ucsalscea@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:aiuv yvmt ftoh gdos}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 500000
          timeout: 500000
          writetimeout: 500000
